#!/bin/sh

. ./../sysoptions.conf

mv /etc/banner /etc/banner_tmp

# add ascii art

DASH_LOGO="
░▒▓███████▓▒░ ░▒▓██████▓▒░ ░▒▓███████▓▒░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░░▒▓██████▓▒░░▒▓████████▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ 
                                                      "

CB_LOGO="       ____      _     _    __        __    _ _ 
      / ___|   _| |__ (_) __\ \      / /_ _| | |
     | |  | | | | '_ \| |/ __\ \ /\ / / _  | | |
     | |__| |_| | |_) | | (__ \ V  V / (_| | | |
      \____\__,_|_.__/|_|\___| \_/\_/ \__,_|_|_|"

if [ "$SYSTEM_TYPE" = "cubicwall" ]; then
	echo "$CB_LOGO" > /etc/banner
	cwversion=$(uci get cubicwall.@main[0].version)
elif [ "$SYSTEM_TYPE" = "dash" ]; then
	echo "$DASH_LOGO" > /etc/banner
	cwversion="Dash"
fi

echo " " >> /etc/banner
echo "   (c) Copyright 2019,2020,2021,2022 XCogia Group" >> /etc/banner

# add Omega firmware version
version=$(uci get onion.@onion[0].version)
build=$(uci get onion.@onion[0].build)

echo " --------------------------------------------------" >> /etc/banner
echo "           CWv$cwversion  Ω-ware: $version b$build" >> /etc/banner
echo " --------------------------------------------------" >> /etc/banner

rm /etc/banner_tmp

