#!/bin/sh

. ./../sysoptions.conf

HOST="$(uci get system.@system[0].hostname)"

uci -q batch << EOF > /dev/null

    set wireless.radio0.disabled='0'
    set wireless.radio0.channel='auto'
    set wireless.client=wifi-iface
    set wireless.client.encryption='psk2'
    set wireless.client.disabled='0'
    set wireless.client.disassoc_low_ack='0'
    set wireless.client.network='wwan'
    set wireless.client.ifname='apcli0'
    set wireless.client.device='radio0'

    set wireless.default_radio0=wifi-iface
    set wireless.default_radio0.device='radio0'
    set wireless.default_radio0.network='lan'
    set wireless.default_radio0.mode='ap'
    set wireless.default_radio0.ssid=$HOST
    set wireless.default_radio0.disable='0'
    set wireless.default_radio0.hidden='0'
    set wireless.default_radio0.encryption='psk2'
    set wireless.default_radio0.key='gnkdsjhfksfksgf;isyuf'

	if [ -n $TEST_SYSTEM -a "$TEST_SYSTEM" = "y" ]; then
        set wireless.client.ssid='Brevsville-UBNT'
        set wireless.client.key='e8c0ec615d3f81e89e4e2dd9bd'
	fi

    commit
EOF
wifi
exit 0

