VERSION="23.05.3"
VCODE="r238"
MODELS="onion"
ALL_KMODS=1
OPENWRT_TAG=v23.05.3
GIT_OPENWRT="https://github.com/openwrt/openwrt"
OEM=crispyoz
DEV_CLEAN_SKIP=1
VERBOSE=1
SILENT=0
NO_LUCI=1
INCLUDE_PACKAGES_M="i2c-tools"
INCLUDE_PACKAGES_Y="omega2-ctrl
i2c-tools
openssh-sftp-server
libsqlite3
libubox
libubus
ubox
ubus
dosfstools
php8
php8-cli
php8-cgi
php8-mod-curl
php8-mod-session
php8-fastcgi
sqlite3-cli
mosquitto-client-ssl
uhttpd
uhttpd-mod-ubus
rpcd
php8-mod-pdo
php8-mod-pdo-sqlite
-dnsmasq
omega2-script
kmod-pwm-mediatek-ramips
kmod-p44-ledchain
dtc"
