VERSION="23.05.3"
VCODE="r238"
MODELS="onion"
ALL_KMODS=1
OPENWRT_TAG=v23.05.3
GIT_OPENWRT="https://github.com/openwrt/openwrt"
OEM=crispyoz
DEV_CLEAN_SKIP=1
VERBOSE=1
SILENT=0
NO_LUCI=1
APPLY_PATCH=1
INCLUDE_PACKAGES_M="i2c-tools"
INCLUDE_PACKAGES_Y="omega2-ctrl i2c-tools openssh-sftp-server libsqlite3 libubox libubus ubox ubus dtc omega2-script"
