#!/bin/sh /etc/rc.common
#
# Author: chris
#
# Created on 23 Dec. 2024, 15:21

#PROCD_DEBUG=1  # uncomment for debug output

START=90
STOP=25
USE_PROCD=1
DAEMON=/usr/sbin/cubicwalld
              
                           
start_service() {
	procd_open_instance cw 
	procd_set_param command $DAEMON -a
	procd_set_param respawn                                                                                                               
	procd_set_param pidfile /var/run/cubicwalld.pid # write a pid file on instance start and remove it on stop
	procd_close_instance                                             
}                                                  
                            
stop_service() {
		procd_send_signal cubicwalld cw SIGTERM
}                           

reload_service() {
         procd_send_signal cubicwalld cw SIGUSR2
} 

service_triggers()
{
        procd_add_reload_interface_trigger apcli0
}

