<?php
$timezoneselected = false;
$wifiselected = false;
$passwordadded = false;
$dataconsent = false;
$acceptlicense =  false;
$finalstep = false;


if(!empty($_POST)) {
    $timezoneselected = !empty($_POST['timezone']) ;
    $wifiselected = !empty($_POST['wifi']);
    $passwordadded = !empty($_POST['password']);
    $dataconsent = isset($_POST['dataconsent']);
    $acceptlicense =  isset($_POST['acceptlicense']);
    $finalstep = !empty($_POST['finalstep']);
    
    if(!empty($_POST['submitit'])) {
        openlog('php', LOG_CONS | LOG_NDELAY | LOG_PID, LOG_USER | LOG_PERROR);    
        syslog(LOG_ERR, 'Timezone: ' . $_POST['timezone']);
        syslog(LOG_ERR, 'Wifi: ' . $_POST['wifi']);
        syslog(LOG_ERR, 'Password: ' . $_POST['password']);
        syslog(LOG_ERR, 'Data Consent: ' . $_POST['dataconsent']);
        syslog(LOG_ERR, 'License Accepted: ' . $_POST['acceptlicense']);
        closelog();

        $timezone_string = explode('|', $_POST['timezone']);
        $post_data = ['jsonrpc' => '2.0',
            'id' => 1,
            'method' => 'call',
            'params' => [
                0 => $_SESSION['ubus_rpc_session'],
                1 => 'uci',
                2 => 'set',
                3 => [
                    'config' => 'system',
                    'type' => 'system',
                    'values' => [
                        'timezone' => $timezone_string[1],
                        'zonename' => $timezone_string[0],
                    ],
                ],
            ],
        ];

        $time_zone_response = $api->process_api($api_method, json_encode($post_data));

        $post_data = [
            'jsonrpc' => '2.0',
            'id' => 1,
            'method' => 'call',
            'params' => [
                0 => $_SESSION['ubus_rpc_session'],
                1 => 'uci',
                2 => 'commit',
                3 => [
                    'config' => 'system',
                ],
            ],
        ];
        $system_commit_response = $api->process_api($api_method, json_encode($post_data));
        
        $post_data = ['jsonrpc' => '2.0',
            'id' => 1,
            'method' => 'call',
            'params' => [
                0 => $_SESSION['ubus_rpc_session'],
                1 => 'uci',
                2 => 'add',
                3 => [
                    'config' => 'wireless',
                    'type' => 'wifi-config',
                ],
            ],
        ];
        $wifi_config_response = $api->process_api($api_method, json_encode($post_data));
          
        $wifi_string = explode('|', $_POST['wifi']);
        $post_data = ['jsonrpc' => '2.0',
            'id' => 1,
            'method' => 'call',
            'params' => [
                0 => $_SESSION['ubus_rpc_session'],
                1 => 'uci',
                2 => 'set',
                3 => [
                    'config' => 'wireless',
                    'type' => 'wifi-config',
                    'values' => [
                        'key' => $_POST['password'],
                        'ssid' =>$wifi_string[0],
                        'encryption' => $wifi_string[1]
                    ]
                ],
            ],
        ];
        $wifi_params_response = $api->process_api($api_method, json_encode($post_data));
        
        $post_data = ['jsonrpc' => '2.0',
            'id' => 1,
            'method' => 'call',
            'params' => [
                0 => $_SESSION['ubus_rpc_session'],
                1 => 'uci',
                2 => 'set',
                3 => [
                    'config' => 'wireless',
                    'section' => 'sta',
                    'values' => [
                        'key' => $_POST['password'],
                        'ssid' => $wifi_string[0],
                        'encryption' => $wifi_string[1],
                        'disabled' => '0'
                    ]
                ],
            ],
        ];
        $wifi_params_response = $api->process_api($api_method, json_encode($post_data));
        

// save the date and ip when the license was accepted

        $post_data = ['jsonrpc' => '2.0',
            'id' => 1,
            'method' => 'call',
            'params' => [
                0 => $_SESSION['ubus_rpc_session'],
                1 => 'uci',
                2 => 'add',
                3 => [
                    'config' => 'cubicwall',
                    'type' => 'license'
                ],
            ],
        ];
        
        $cw_params_response = $api->process_api($api_method, json_encode($post_data));
        
        $post_data = ['jsonrpc' => '2.0',
            'id' => 1,
            'method' => 'call',
            'params' => [
                0 => $_SESSION['ubus_rpc_session'],
                1 => 'uci',
                2 => 'set',
                3 => [
                    'config' => 'cubicwall',
                    'type' => 'license',
                    'values' => [
                        'license_accepted' => $_POST['acceptlicense'],
                        'data_collection' => $_POST['dataconsent'],
                        'accepted_by' => gethostbyaddr($_SERVER['REMOTE_ADDR'])
                    ]
                ],
            ],
        ];
        
        $cw_params_response = $api->process_api($api_method, json_encode($post_data));

        $post_data = [
            'jsonrpc' => '2.0',
            'id' => 1,
            'method' => 'call',
            'params' => [
                0 => $_SESSION['ubus_rpc_session'],
                1 => 'uci',
                2 => 'commit',
                3 => [
                    'config' => 'cubicwall'
                ],
            ],
        ];
        
        $cw_commit_res = $api->process_api($api_method, json_encode($post_data));             
        
        // Always comit wireless stuff last as it triggers a reboot (hotplug script)
        $post_data = [
            'jsonrpc' => '2.0',
            'id' => 1,
            'method' => 'call',
            'params' => [
                0 => $_SESSION['ubus_rpc_session'],
                1 => 'uci',
                2 => 'commit',
                3 => [
                    'config' => 'wireless',
                ],
            ],
        ];
        $wifi_commit_res = $api->process_api($api_method, json_encode($post_data));             

    }
}



$timezones = [
    'Australia/Adelaide|CST-9:30CST,M10.1.0,M4.1.0/3' => 'Australia/Adelaide',
    'Australia/Brisbane|EST-10' => 'Australia/Brisbane',
    'Australia/Broken Hill|CST-9:30CST,M10.1.0,M4.1.0/3' => 'Australia/Broken Hill',
    'Australia/Currie|EST-10EST,M10.1.0,M4.1.0/3' => 'Australia/Currie',
    'Australia/Darwin|CST-9:30' => 'Australia/Darwin',
    'Australia/Eucla|CWST-8:45' => 'Australia/Eucla',
    'Australia/Hobart|EST-10EST,M10.1.0,M4.1.0/3' => 'Australia/Hobart',
    'Australia/Lindeman|EST-10' => 'Australia/Lindeman',
    'Australia/Lord Howe|LHST-10:30LHST-11,M10.1.0,M4.1.0' => 'Australia/Lord Howe',
    'Australia/Melbourne|EST-10EST,M10.1.0,M4.1.0/3' => 'Australia/Melbourne',
    'Australia/Perth|WST-8' => 'Australia/Perth',    
    'Australia/Sydney|EST-10EST,M10.1.0,M4.1.0/3' => 'Australia/Sydney',
    'Africa/Abidjan|GMT0' => 'Africa/Abidjan',
    'Africa/Accra|GMT0' => 'Africa/Accra',
    'Africa/Addis Ababa|EAT-3' => 'Africa/Addis Ababa',
    'Africa/Algiers|CET-1' => 'Africa/Algiers',
    'Africa/Asmara|EAT-3' => 'Africa/Asmara',
    'Africa/Bamako|GMT0' => 'Africa/Bamako',
    'Africa/Bangui|WAT-1' => 'Africa/Bangui',
    'Africa/Banjul|GMT0' => 'Africa/Banjul',
    'Africa/Bissau|GMT0' => 'Africa/Bissau',
    'Africa/Blantyre|CAT-2' => 'Africa/Blantyre',
    'Africa/Brazzaville|WAT-1' => 'Africa/Brazzaville',
    'Africa/Bujumbura|CAT-2' => 'Africa/Bujumbura',
    'Africa/Casablanca|WET0' => 'Africa/Casablanca',
    'Africa/Ceuta|CET-1CEST,M3.5.0,M10.5.0/3' => 'Africa/Ceuta',
    'Africa/Conakry|GMT0' => 'Africa/Conakry',
    'Africa/Dakar|GMT0' => 'Africa/Dakar',
    'Africa/Dar es Salaam|EAT-3' => 'Africa/Dar es Salaam',
    'Africa/Djibouti|EAT-3' => 'Africa/Djibouti',
    'Africa/Douala|WAT-1' => 'Africa/Douala',
    'Africa/El Aaiun|WET0' => 'Africa/El Aaiun',
    'Africa/Freetown|GMT0' => 'Africa/Freetown',
    'Africa/Gaborone|CAT-2' => 'Africa/Gaborone',
    'Africa/Harare|CAT-2' => 'Africa/Harare',
    'Africa/Johannesburg|SAST-2' => 'Africa/Johannesburg',
    'Africa/Kampala|EAT-3' => 'Africa/Kampala',
    'Africa/Khartoum|EAT-3' => 'Africa/Khartoum',
    'Africa/Kigali|CAT-2' => 'Africa/Kigali',
    'Africa/Kinshasa|WAT-1' => 'Africa/Kinshasa',
    'Africa/Lagos|WAT-1' => 'Africa/Lagos',
    'Africa/Libreville|WAT-1' => 'Africa/Libreville',
    'Africa/Lome|GMT0' => 'Africa/Lome',
    'Africa/Luanda|WAT-1' => 'Africa/Luanda',
    'Africa/Lubumbashi|CAT-2' => 'Africa/Lubumbashi',
    'Africa/Lusaka|CAT-2' => 'Africa/Lusaka',
    'Africa/Malabo|WAT-1' => 'Africa/Malabo',
    'Africa/Maputo|CAT-2' => 'Africa/Maputo',
    'Africa/Maseru|SAST-2' => 'Africa/Maseru',
    'Africa/Mbabane|SAST-2' => 'Africa/Mbabane',
    'Africa/Mogadishu|EAT-3' => 'Africa/Mogadishu',
    'Africa/Monrovia|GMT0' => 'Africa/Monrovia',
    'Africa/Nairobi|EAT-3' => 'Africa/Nairobi',
    'Africa/Ndjamena|WAT-1' => 'Africa/Ndjamena',
    'Africa/Niamey|WAT-1' => 'Africa/Niamey',
    'Africa/Nouakchott|GMT0' => 'Africa/Nouakchott',
    'Africa/Ouagadougou|GMT0' => 'Africa/Ouagadougou',
    'Africa/Porto-Novo|WAT-1' => 'Africa/Porto-Novo',
    'Africa/Sao Tome|GMT0' => 'Africa/Sao Tome',
    'Africa/Tripoli|EET-2' => 'Africa/Tripoli',
    'Africa/Tunis|CET-1' => 'Africa/Tunis',
    'Africa/Windhoek|WAT-1WAST,M9.1.0,M4.1.0' => 'Africa/Windhoek',
    'America/Adak|HAST10HADT,M3.2.0,M11.1.0' => 'America/Adak',
    'America/Anchorage|AKST9AKDT,M3.2.0,M11.1.0' => 'America/Anchorage',
    'America/Anguilla|AST4' => 'America/Anguilla',
    'America/Antigua|AST4' => 'America/Antigua',
    'America/Araguaina|BRT3' => 'America/Araguaina',
    'America/Argentina/Buenos Aires|ART3' => 'America/Argentina/Buenos Aires',
    'America/Argentina/Catamarca|ART3' => 'America/Argentina/Catamarca',
    'America/Argentina/Cordoba|ART3' => 'America/Argentina/Cordoba',
    'America/Argentina/Jujuy|ART3' => 'America/Argentina',
    'America/Argentina/La Rioja|ART3' => 'America/Argentina/La Rioja',
    'America/Argentina/Mendoza|ART3' => 'America/Argentina/Mendoza',
    'America/Argentina/Rio Gallegos|ART3' => 'America/Argentina/Rio Gallegos',
    'America/Argentina/Salta|ART3' => 'America/Argentina/Salta',
    'America/Argentina/San Juan|ART3' => 'America/Argentina/San Juan',
    'America/Argentina/Tucuman|ART3' => 'America/Argentina/Tucuman',
    'America/Argentina/Ushuaia|ART3' => 'America/Argentina/Ushuaia',
    'America/Aruba|AST4' => 'America/Aruba',
    'America/Asuncion|PYT4PYST,M10.1.0/0,M4.2.0/0' => 'America/Asuncion',
    'America/Atikokan|EST5' => 'America/Atikokan',
    'America/Bahia|BRT3' => 'America/Bahia',
    'America/Barbados|AST4' => 'America/Barbados',
    'America/Belem|BRT3' => 'America/Belem',
    'America/Belize|CST6' => 'America/Belize',
    'America/Blanc-Sablon|AST4' => 'America/Blanc-Sablon',
    'America/Boa Vista|AMT4' => 'America/Boa Vista',
    'America/Bogota|COT5' => 'America/Bogota',
    'America/Boise|MST7MDT,M3.2.0,M11.1.0' => 'America/Boise',
    'America/Cambridge Bay|MST7MDT,M3.2.0,M11.1.0' => 'America/Cambridge Bay',
    'America/Campo Grande|AMT4AMST,M10.3.0/0,M2.3.0/0' => 'America/Campo Grand',
    'America/Cancun|CST6CDT,M4.1.0,M10.5.0' => 'America/Cancun',
    'America/Caracas|VET4:30' => 'America/Caracas',
    'America/Cayenne|GFT3' => 'America/Cayenne',
    'America/Cayman|EST5' => 'America/Cayman',
    'America/Chicago|CST6CDT,M3.2.0,M11.1.0' => 'America/Chicago',
    'America/Chihuahua|MST7MDT,M4.1.0,M10.5.0' => 'America/Chihuahua',
    'America/Costa Rica|CST6' => 'America/Costa Rica',
    'America/Cuiaba|AMT4AMST,M10.3.0/0,M2.3.0/0' => 'America/Cuiaba',
    'America/Curacao|AST4' => 'America/Curacao',
    'America/Danmarkshavn|GMT0' => 'America/Danmarkshavn',
    'America/Dawson|PST8PDT,M3.2.0,M11.1.0' => 'America/Dawson',
    'America/Dawson Creek|MST7' => 'America/Dawson Creek',
    'America/Denver|MST7MDT,M3.2.0,M11.1.0' => 'America/Denver',
    'America/Detroit|EST5EDT,M3.2.0,M11.1.0' => 'America/Detroit',
    'America/Dominica|AST4' => 'America/Dominica',
    'America/Edmonton|MST7MDT,M3.2.0,M11.1.0' => 'America/Edmonton',
    'America/Eirunepe|AMT4' => 'America/Eirunepe',
    'America/El Salvador|CST6' => 'America/El Salvador',
    'America/Fortaleza|BRT3' => 'America/Fortaleza',
    'America/Glace Bay|AST4ADT,M3.2.0,M11.1.0' => 'America/Glace Bay',
    'America/Goose Bay|AST4ADT,M3.2.0/0:01,M11.1.0/0:01' => 'America/Goose Bay',
    'America/Grand Turk|EST5EDT,M3.2.0,M11.1.0' => 'America/Grand Turk',
    'America/Grenada|AST4' => 'America/Grenada',
    'America/Guadeloupe|AST4' => 'America/Guadeloupe',
    'America/Guatemala|CST6' => 'America/Guatemala',
    'America/Guayaquil|ECT5' => 'America/Guayaquil',
    'America/Guyana|GYT4' => 'America/Guyana',
    'America/Halifax|AST4ADT,M3.2.0,M11.1.0' => 'America/Halifax',
    'America/Havana|CST5CDT,M3.2.0/0,M10.5.0/1' => 'America/Havana',
    'America/Hermosillo|MST7' => 'America/Hermosillo',
    'America/Indiana/Indianapolis|EST5EDT,M3.2.0,M11.1.0' => 'America/Indiana/Indianapolis',
    'America/Indiana/Knox|CST6CDT,M3.2.0,M11.1.0' => 'America/Indiana/Knox',
    'America/Indiana/Marengo|EST5EDT,M3.2.0,M11.1.0' => 'America/Indiana/Marengo',
    'America/Indiana/Petersburg|EST5EDT,M3.2.0,M11.1.0' => 'America/Indiana/Petersburg',
    'America/Indiana/Tell City|CST6CDT,M3.2.0,M11.1.0' => 'America/Indiana/Tell City',
    'America/Indiana/Vevay|EST5EDT,M3.2.0,M11.1.0' => 'America/Indiana/Vevay',
    'America/Indiana/Vincennes|EST5EDT,M3.2.0,M11.1.0' => 'America/Indiana/Vincennes',
    'America/Indiana/Winamac|EST5EDT,M3.2.0,M11.1.0' => 'America/Indiana/Winamac',
    'America/Inuvik|MST7MDT,M3.2.0,M11.1.0' => 'America/Inuvik',
    'America/Iqaluit|EST5EDT,M3.2.0,M11.1.0' => 'America/Iqaluit',
    'America/Jamaica|EST5' => 'America/Jamaica',
    'America/Juneau|AKST9AKDT,M3.2.0,M11.1.0' => 'America/Juneau',
    'America/Kentucky/Louisville|EST5EDT,M3.2.0,M11.1.0' => 'America/Kentucky/Louisville',
    'America/Kentucky/Monticello|EST5EDT,M3.2.0,M11.1.0' => 'America/Kentucky/Monticello',
    'America/La Paz|BOT4' => 'America/La Paz',
    'America/Lima|PET5' => 'America/Lima',
    'America/Los Angeles|PST8PDT,M3.2.0,M11.1.0' => 'America/Los Angeles',
    'America/Maceio|BRT3' => 'America/Maceio',
    'America/Managua|CST6' => 'America/Managua',
    'America/Manaus|AMT4' => 'America/Manaus',
    'America/Marigot|AST4' => 'America/Marigot',
    'America/Martinique|AST4' => 'America/Martiniqu',
    'America/Matamoros|CST6CDT,M3.2.0,M11.1.0' => 'America/Matamoros',
    'America/Mazatlan|MST7MDT,M4.1.0,M10.5.0' => 'America/Mazatlan',
    'America/Menominee|CST6CDT,M3.2.0,M11.1.0' => 'America/Menominee',
    'America/Merida|CST6CDT,M4.1.0,M10.5.0' => 'America/Merida',
    'America/Mexico City|CST6CDT,M4.1.0,M10.5.0' => 'America/Mexico City',
    'America/Miquelon|PMST3PMDT,M3.2.0,M11.1.0' => 'America/Miquelon',
    'America/Moncton|AST4ADT,M3.2.0,M11.1.0' => 'America/Moncton',
    'America/Monterrey|CST6CDT,M4.1.0,M10.5.0' => 'America/Monterrey',
    'America/Montevideo|UYT3UYST,M10.1.0,M3.2.0' => 'America/Montevideo',
    'America/Montreal|EST5EDT,M3.2.0,M11.1.0' => 'America/Montreal',
    'America/Montserrat|AST4' => 'America/Montserrat',
    'America/Nassau|EST5EDT,M3.2.0,M11.1.0' => 'America/Nassau',
    'America/New York|EST5EDT,M3.2.0,M11.1.0' => 'America/New York',
    'America/Nipigon|EST5EDT,M3.2.0,M11.1.0' => 'America/Nipigon',
    'America/Nome|AKST9AKDT,M3.2.0,M11.1.0' => 'America/Nome',
    'America/Noronha|FNT2' => 'America/Noronha',
    'America/North Dakota/Center|CST6CDT,M3.2.0,M11.1.0' => 'America/North Dakota/Center',
    'America/North Dakota/New Salem|CST6CDT,M3.2.0,M11.1.0' => 'America/North Dakota/New Salem',
    'America/Ojinaga|MST7MDT,M3.2.0,M11.1.0' => 'America/Ojinaga',
    'America/Panama|EST5' => 'America/Panama',
    'America/Pangnirtung|EST5EDT,M3.2.0,M11.1.0' => 'America/Pangnirtung',
    'America/Paramaribo|SRT3' => 'America/Paramaribo',
    'America/Phoenix|MST7' => 'America/Phoenix',
    'America/Port of Spain|AST4' => 'America/Port of Spain',
    'America/Port-au-Prince|EST5' => 'America/Port-au-Prince',
    'America/Porto Velho|AMT4' => 'America/Porto Velho',
    'America/Puerto Rico|AST4' => 'America/Puerto Rico',
    'America/Rainy River|CST6CDT,M3.2.0,M11.1.0' => 'America/Rainy River',
    'America/Rankin Inlet|CST6CDT,M3.2.0,M11.1.0' => 'Rankin Inlet',
    'America/Recife|BRT3' => 'America/Recife',
    'America/Regina|CST6' => 'America/Regina',
    'America/Rio Branco|AMT4' => 'America/Rio Branco',
    'America/Santa Isabel|PST8PDT,M4.1.0,M10.5.0' => 'America/Santa Isabel',
    'America/Santarem|BRT3' => 'America/Santarem',
    'America/Santo Domingo|AST4' => 'America/Santo Domingo',
    'America/Sao Paulo|BRT3BRST,M10.3.0/0,M2.3.0/0' => 'America/Sao Paulo',
    'America/Scoresbysund|EGT1EGST,M3.5.0/0,M10.5.0/1' => 'America/Scoresbysund',
    'America/Shiprock|MST7MDT,M3.2.0,M11.1.0' => 'America/Shiprock',
    'America/St Barthelemy|AST4' => 'America/St Barthelemy',
    'America/St Johns|NST3:30NDT,M3.2.0/0:01,M11.1.0/0:01' => 'America/St Johns',
    'America/St Kitts|AST4' => 'America/St Kitts',
    'America/St Lucia|AST4' => 'America/St Lucia',
    'America/St Thomas|AST4' => 'America/St Thomas',
    'America/St Vincent|AST4' => 'America/St Vincent',
    'America/Swift Current|CST6' => 'America/Swift Current',
    'America/Tegucigalpa|CST6' => 'America/Tegucigalpa',
    'America/Thule|AST4ADT,M3.2.0,M11.1.0' => 'America/Thule',
    'America/Thunder Bay|EST5EDT,M3.2.0,M11.1.0' => 'America/Thunder Bay',
    'America/Tijuana|PST8PDT,M3.2.0,M11.1.0' => 'America/Tijuana',
    'America/Toronto|EST5EDT,M3.2.0,M11.1.0' => 'America/Toronto',
    'America/Tortola|AST4' => 'America/Tortola',
    'America/Vancouver|PST8PDT,M3.2.0,M11.1.0' => 'America/Vancouver',
    'America/Whitehorse|PST8PDT,M3.2.0,M11.1.0' => 'America/Whitehorse',
    'America/Winnipeg|CST6CDT,M3.2.0,M11.1.0' => 'America/Winnipeg',
    'America/Yakutat|AKST9AKDT,M3.2.0,M11.1.0' => 'America/Yakutat',
    'America/Yellowknife|MST7MDT,M3.2.0,M11.1.0' => '"America/Yellowknife',
    'Antarctica/Casey|WST-8' => 'Antarctica/Casey',
    'Antarctica/Davis|DAVT-7' => 'Antarctica/Davis',
    'Antarctica/DumontDUrville|DDUT-10' => 'Antarctica/DumontDUrville',
    'Antarctica/Macquarie|MIST-11' => 'Antarctica/Macquarie',
    'Antarctica/Mawson|MAWT-5' => 'Antarctica/Mawson',
    'Antarctica/McMurdo|NZST-12NZDT,M9.5.0,M4.1.0/3' => 'Antarctica/McMurdo',
    'Antarctica/Rothera|ROTT3' => 'Antarctica/Rothera',
    'Antarctica/South Pole|NZST-12NZDT,M9.5.0,M4.1.0/3' => 'Antarctica/South Pole',
    'Antarctica/Syowa|SYOT-3' => 'Antarctica/Syowa',
    'Antarctica/Vostok|VOST-6' => 'Antarctica/Vostok',
    'Arctic/Longyearbyen|CET-1CEST,M3.5.0,M10.5.0/3' => 'Arctic/Longyearbyen',
    'Asia/Aden|AST-3' => 'Asia/Aden',
    'Asia/Almaty|ALMT-6' => 'Asia/Almaty',
    'Asia/Anadyr|ANAT-11ANAST,M3.5.0,M10.5.0/3' => 'Asia/Anadyr',
    'Asia/Aqtau|AQTT-5' => 'Asia/Aqtau',
    'Asia/Aqtobe|AQTT-5' => 'Asia/Aqtobe',
    'Asia/Ashgabat|TMT-5' => 'Asia/Ashgabat',
    'Asia/Baghdad|AST-3' => 'Asia/Baghdad',
    'Asia/Bahrain|AST-3' => 'Asia/Bahrain',
    'Asia/Baku|AZT-4AZST,M3.5.0/4,M10.5.0/5' => 'Asia/Baku',
    'Asia/Bangkok|ICT-7' => 'Asia/Bangkok',
    'Asia/Beirut|EET-2EEST,M3.5.0/0,M10.5.0/0' => 'Asia/Beirut',
    'Asia/Bishkek|KGT-6' => 'Asia/Bishkek',
    'Asia/Brunei|BNT-8' => 'Asia/Brunei',
    'Asia/Choibalsan|CHOT-8' => 'Asia/Choibalsan',
    'Asia/Chongqing|CST-8' => 'Asia/Chongqing',
    'Asia/Colombo|IST-5:30' => 'Asia/Colombo',
    'Asia/Damascus|EET-2EEST,M4.1.5/0,M10.5.5/0' => 'Asia/Damascus',
    'Asia/Dhaka|BDT-6' => 'Asia/Dhaka',
    'Asia/Dili|TLT-9' => 'Asia/Dili',
    'Asia/Dubai|GST-4' => 'Asia/Dubai',
    'Asia/Dushanbe|TJT-5' => 'Asia/Dushanbe',
    'Asia/Gaza|EET-2EEST,M3.5.6/0:01,M9.1.5' => 'Asia/Gaza',
    'Asia/Harbin|CST-8' => 'Asia/Harbin',
    'Asia/Ho Chi Minh|ICT-7' => 'Asia/Ho Chi Minh',
    'Asia/Hong Kong|HKT-8' => 'Asia/Hong Kong',
    'Asia/Hovd|HOVT-7' => 'Asia/Hovd',
    'Asia/Irkutsk|IRKT-8IRKST,M3.5.0,M10.5.0/3' => 'Asia/Irkutsk',
    'Asia/Jakarta|WIT-7' => 'Asia/Jakarta',
    'Asia/Jayapura|EIT-9' => 'Asia/Jayapura',
    'Asia/Kabul|AFT-4:30' => 'Asia/Kabul',
    'Asia/Kamchatka|PETT-11PETST,M3.5.0,M10.5.0/3' => 'Asia/Kamchatka',
    'Asia/Karachi|PKT-5' => 'Asia/Karachi',
    'Asia/Kashgar|CST-8' => 'Asia/Kashgar',
    'Asia/Kathmandu|NPT-5:45' => 'Asia/Kathmandu',
    'Asia/Kolkata|IST-5:30' => 'Asia/Kolkata',
    'Asia/Krasnoyarsk|KRAT-7KRAST,M3.5.0,M10.5.0/3' => 'Asia/Krasnoyarsk',
    'Asia/Kuala Lumpur|MYT-8' => 'Asia/Kuala Lumpur',
    'Asia/Kuching|MYT-8' => 'Asia/Kuching',
    'Asia/Kuwait|AST-3' => 'Asia/Kuwait',
    'Asia/Macau|CST-8' => 'Asia/Macau',
    'Asia/Magadan|MAGT-11MAGST,M3.5.0,M10.5.0/3' => 'Asia/Magadan',
    'Asia/Makassar|CIT-8' => 'Asia/Makassar',
    'Asia/Manila|PHT-8' => 'Asia/Manila',
    'Asia/Muscat|GST-4' => 'Asia/Muscat',
    'Asia/Nicosia|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Asia/Nicosia',
    'Asia/Novokuznetsk|NOVT-6NOVST,M3.5.0,M10.5.0/3' => 'Asia/Novokuznetsk',
    'Asia/Novosibirsk|NOVT-6NOVST,M3.5.0,M10.5.0/3' => 'Asia/Novosibirsk',
    'Asia/Omsk|OMST-7' => 'Asia/Omsk',
    'Asia/Oral|ORAT-5' => 'Asia/Oral',
    'Asia/Phnom Penh|ICT-7' => 'Asia/Phnom Penh',
    'Asia/Pontianak|WIT-7' => 'Asia/Pontianak',
    'Asia/Pyongyang|KST-9' => 'Asia/Pyongyang',
    'Asia/Qatar|AST-3' => 'Asia/Qatar',
    'Asia/Qyzylorda|QYZT-6' => 'Asia/Qyzylorda',
    'Asia/Rangoon|MMT-6:30' => 'Asia/Rangoon',
    'Asia/Riyadh|AST-3' => 'Asia/Riyadh',
    'Asia/Sakhalin|SAKT-10SAKST,M3.5.0,M10.5.0/3' => 'Asia/Sakhalin',
    'Asia/Samarkand|UZT-5' => 'Asia/Samarkand',
    'Asia/Seoul|KST-9' => 'Asia/Seoul',
    'Asia/Shanghai|CST-8' => 'Asia/Shanghai',
    'Asia/Singapore|SGT-8' => 'Asia/Singapore',
    'Asia/Taipei|CST-8' => 'Asia/Taipei',
    'Asia/Tashkent|UZT-5' => 'Asia/Tashkent',
    'Asia/Tbilisi|GET-4' => 'Asia/Tbilisi',
    'Asia/Tehran|IRST-3:30IRDT,80/0,264/0' => 'Asia/Tehran',
    'Asia/Thimphu|BTT-6' => 'Asia/Thimphu',
    'Asia/Tokyo|JST-9' => 'Asia/Tokyo',
    'Asia/Ulaanbaatar|ULAT-8' => 'Asia/Ulaanbaatar',
    'Asia/Urumqi|CST-8' => 'Asia/Urumqi',
    'Asia/Vientiane|ICT-7' => 'Asia/Vientiane',
    'Asia/Vladivostok|VLAT-10VLAST,M3.5.0,M10.5.0/3' => 'Asia/Vladivostok',
    'Asia/Yakutsk|YAKT-9YAKST,M3.5.0,M10.5.0/3' => 'Asia/Yakutsk',
    'Asia/Yekaterinburg|YEKT-5YEKST,M3.5.0,M10.5.0/3' => 'Asia/Yekaterinburg',
    'Asia/Yerevan|AMT-4AMST,M3.5.0,M10.5.0/3' => 'Asia/Yerevan',
    'Atlantic/Azores|AZOT1AZOST,M3.5.0/0,M10.5.0/1' => 'Atlantic/Azores',
    'Atlantic/Bermuda|AST4ADT,M3.2.0,M11.1.0' => 'Atlantic/Bermuda',
    'Atlantic/Canary|WET0WEST,M3.5.0/1,M10.5.0' => 'Atlantic/Canary',
    'Atlantic/Cape Verde|CVT1' => 'Atlantic/Cape Verde',
    'Atlantic/Faroe|WET0WEST,M3.5.0/1,M10.5.0' => 'Atlantic/Faroe',
    'Atlantic/Madeira|WET0WEST,M3.5.0/1,M10.5.0' => 'Atlantic/Madeira',
    'Atlantic/Reykjavik|GMT0' => 'Atlantic/Reykjavik',
    'Atlantic/South Georgia|GST2' => 'Atlantic/South Georgia',
    'Atlantic/St Helena|GMT0' => 'Atlantic/St Helena',
    'Atlantic/Stanley|FKT4FKST,M9.1.0,M4.3.0' => 'Atlantic/Stanley',
    'Australia/Adelaide|CST-9:30CST,M10.1.0,M4.1.0/3' => 'Australia/Adelaide',
    'Australia/Brisbane|EST-10' => 'Australia/Brisbane',
    'Australia/Broken Hill|CST-9:30CST,M10.1.0,M4.1.0/3' => 'Australia/Broken Hill',
    'Australia/Currie|EST-10EST,M10.1.0,M4.1.0/3' => 'Australia/Currie',
    'Australia/Darwin|CST-9:30' => 'Australia/Darwin',
    'Australia/Eucla|CWST-8:45' => 'Australia/Eucla',
    'Australia/Hobart|EST-10EST,M10.1.0,M4.1.0/3' => 'Australia/Hobart',
    'Australia/Lindeman|EST-10' => 'Australia/Lindeman',
    'Australia/Lord Howe|LHST-10:30LHST-11,M10.1.0,M4.1.0' => 'Australia/Lord Howe',
    'Australia/Melbourne|EST-10EST,M10.1.0,M4.1.0/3' => 'Australia/Melbourne',
    'Australia/Perth|WST-8' => 'Australia/Perth',
    'Australia/Sydney|EST-10EST,M10.1.0,M4.1.0/3' => 'Australia/Sydney',
    'Europe/Amsterdam|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Amsterdam',
    'Europe/Andorra|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Andorra',
    'Europe/Athens|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Athens',
    'Europe/Belgrade|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Belgrade',
    'Europe/Berlin|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Berlin',
    'Europe/Bratislava|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Bratislava',
    'Europe/Brussels|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Brussels',
    'Europe/Bucharest|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Bucharest',
    'Europe/Budapest|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Budapest',
    'Europe/Chisinau|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Chisinau',
    'Europe/Copenhagen|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Copenhagen',
    'Europe/Dublin|GMT0IST,M3.5.0/1,M10.5.0' => 'Europe/Dublin',
    'Europe/Gibraltar|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Gibraltar',
    'Europe/Guernsey|GMT0BST,M3.5.0/1,M10.5.0' => 'Europe/Guernsey',
    'Europe/Helsinki|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Helsinki',
    'Europe/Isle of Man|GMT0BST,M3.5.0/1,M10.5.0' => 'Europe/Isle of Man',
    'Europe/Istanbul|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Istanbul',
    'Europe/Jersey|GMT0BST,M3.5.0/1,M10.5.0' => 'Europe/Jersey',
    'Europe/Kaliningrad|EET-2EEST,M3.5.0,M10.5.0/3' => 'Europe/Kaliningrad',
    'Europe/Kiev|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Kiev',
    'Europe/Lisbon|WET0WEST,M3.5.0/1,M10.5.0' => 'Europe/Lisbon',
    'Europe/Ljubljana|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Ljubljana',
    'Europe/London|GMT0BST,M3.5.0/1,M10.5.0' => 'Europe/London',
    'Europe/Luxembourg|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Luxembourg',
    'Europe/Madrid|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Madrid',
    'Europe/Malta|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Malta',
    'Europe/Mariehamn|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Mariehamn',
    'Europe/Minsk|EET-2EEST,M3.5.0,M10.5.0/3' => 'Europe/Minsk',
    'Europe/Monaco|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Monaco',
    'Europe/Moscow|MSK-3' => 'Europe/Moscow',
    'Europe/Oslo|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Oslo',
    'Europe/Paris|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Paris',
    'Europe/Podgorica|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Podgorica',
    'Europe/Prague|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Prague',
    'Europe/Riga|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Riga',
    'Europe/Rome|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Rome',
    'Europe/Samara|SAMT-3SAMST,M3.5.0,M10.5.0/3' => 'Europe/Samara',
    'Europe/San Marino|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/San Marino',
    'Europe/Sarajevo|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Sarajevo',
    'Europe/Simferopol|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Simferopol',
    'Europe/Skopje|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Skopje',
    'Europe/Sofia|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Sofia',
    'Europe/Stockholm|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Stockholm',
    'Europe/Tallinn|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Tallinn',
    'Europe/Tirane|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Tirane',
    'Europe/Uzhgorod|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Uzhgorod',
    'Europe/Vaduz|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Vaduz',
    'Europe/Vatican|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Vatican',
    'Europe/Vienna|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Vienna',
    'Europe/Vilnius|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Vilnius',
    'Europe/Volgograd|VOLT-3VOLST,M3.5.0,M10.5.0/3' => 'Europe/Volgograd',
    'Europe/Warsaw|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Warsaw',
    'Europe/Zagreb|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Zagreb',
    'Europe/Zaporozhye|EET-2EEST,M3.5.0/3,M10.5.0/4' => 'Europe/Zaporozhye',
    'Europe/Zurich|CET-1CEST,M3.5.0,M10.5.0/3' => 'Europe/Zurich',
    'Indian/Antananarivo|EAT-3' => 'Indian/Antananarivo',
    'Indian/Chagos|IOT-6' => 'Indian/Chagos',
    'Indian/Christmas|CXT-7' => 'Indian/Christmas',
    'Indian/Cocos|CCT-6:30' => 'Indian/Cocos',
    'Indian/Comoro|EAT-3' => 'Indian/Comoro',
    'Indian/Kerguelen|TFT-5' => 'Indian/Kerguelen',
    'Indian/Mahe|SCT-4' => 'Indian/Mahe',
    'Indian/Maldives|MVT-5' => 'Indian/Maldives',
    'Indian/Mauritius|MUT-4' => 'Indian/Mauritius',
    'Indian/Mayotte|EAT-3' => 'Indian/Mayotte',
    'Indian/Reunion|RET-4' => 'Indian/Reunion',
    'Pacific/Apia|WST11' => 'Pacific/Apia',
    'Pacific/Auckland|NZST-12NZDT,M9.5.0,M4.1.0/3' => 'Pacific/Auckland',
    'Pacific/Chatham|CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45' => 'Pacific/Chatham',
    'Pacific/Efate|VUT-11' => 'Pacific/Efate',
    'Pacific/Enderbury|PHOT-13' => 'Pacific/Enderbury',
    'Pacific/Fakaofo|TKT10' => 'Pacific/Fakaofo',
    'Pacific/Fiji|FJT-12' => 'Pacific/Fiji',
    'Pacific/Funafuti|TVT-12' => 'Pacific/Funafuti',
    'Pacific/Galapagos|GALT6' => 'Pacific/Galapagos',
    'Pacific/Gambier|GAMT9' => 'Pacific/Gambier',
    'Pacific/Guadalcanal|SBT-11' => 'Pacific/Guadalcanal',
    'Pacific/Guam|ChST-10' => 'Pacific/Guam',
    'Pacific/Honolulu|HST10' => 'Pacific/Honolulu',
    'Pacific/Johnston|HST10' => 'Pacific/Johnston',
    'Pacific/Kiritimati|LINT-14' => 'Pacific/Kiritimati',
    'Pacific/Kosrae|KOST-11' => 'Pacific/Kosrae',
    'Pacific/Kwajalein|MHT-12' => 'Pacific/Kwajalein',
    'Pacific/Majuro|MHT-12' => 'Pacific/Majuro',
    'Pacific/Marquesas|MART9:30' => 'Pacific/Marquesas',
    'Pacific/Midway|SST11' => 'Pacific/Midway',
    'Pacific/Nauru|NRT-12' => 'Pacific/Nauru',
    'Pacific/Niue|NUT11' => 'Pacific/Niue',
    'Pacific/Norfolk|NFT-11:30' => 'Pacific/Norfolk',
    'Pacific/Noumea|NCT-11' => 'Pacific/Noumea',
    'Pacific/Pago Pago|SST11' => 'Pacific/Pago Pago',
    'Pacific/Palau|PWT-9' => 'Pacific/Palau',
    'Pacific/Pitcairn|PST8' => 'Pacific/Pitcairn',
    'Pacific/Ponape|PONT-11' => 'Pacific/Ponape',
    'Pacific/Port Moresby|PGT-10' => 'Pacific/Port Moresby',
    'Pacific/Rarotonga|CKT10' => 'Pacific/Rarotonga',
    'Pacific/Saipan|ChST-10' => 'Pacific/Saipan',
    'Pacific/Tahiti|TAHT10' => 'Pacific/Tahiti',
    'Pacific/Tarawa|GILT-12' => 'Pacific/Tarawa',
    'Pacific/Tongatapu|TOT-13' => 'Pacific/Tongatapu',
    'Pacific/Truk|TRUT-10' => 'Pacific/Truk',
    'Pacific/Wake|WAKT-12' => 'Pacific/Wake',
    'Pacific/Wallis|WFT-12' => 'Pacific/Wallis'
  ];
  
?>
